begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(10);
select ok(not has_table_privilege('anon', 'public.contact_submissions', 'INSERT'), 'Anonymous contact inserts cannot bypass verification');
select ok(not has_table_privilege('anon', 'public.newsletter_subscriptions', 'INSERT'), 'Anonymous newsletter inserts cannot bypass verification');
select ok(not has_table_privilege('authenticated', 'public.contact_submissions', 'INSERT'), 'Signed-in contact inserts cannot bypass verification');
select ok(not has_table_privilege('authenticated', 'public.newsletter_subscriptions', 'INSERT'), 'Signed-in newsletter inserts cannot bypass verification');
select ok(has_table_privilege('service_role', 'public.contact_submissions', 'INSERT'), 'Verified service may store contact');
select ok(has_table_privilege('service_role', 'public.newsletter_subscriptions', 'INSERT'), 'Verified service may store newsletter');
select is((select count(*)::int from pg_policies where schemaname = 'public' and tablename in ('contact_submissions', 'newsletter_subscriptions') and cmd = 'INSERT' and policyname in ('Anyone can submit contact form', 'Anyone can subscribe to newsletter')), 0, 'Legacy insert policies are retired');
set local role service_role;
insert into public.contact_submissions(name,email,role,message,source) values ('Form contract', 'hcaptcha-contact@example.test', 'Founder', 'Verified synthetic contact', 'contact_page');
insert into public.newsletter_subscriptions(email) values ('hcaptcha-newsletter@example.test');
reset role;
select is((select count(*)::int from public.contact_submissions where email = 'hcaptcha-contact@example.test'), 1, 'Service insertion works under RLS');
select is((select count(*)::int from public.newsletter_subscriptions where email = 'hcaptcha-newsletter@example.test'), 1, 'Service newsletter insertion works under RLS');
select is((select count(*)::int from pg_policies where schemaname = 'public' and cmd = 'SELECT' and ((tablename = 'contact_submissions' and policyname = 'Admins can read contact submissions') or (tablename = 'newsletter_subscriptions' and policyname = 'Admins can read newsletter subscriptions'))), 2, 'Existing scoped admin read policies are retained without granting browser SELECT');
select * from finish();
rollback;
