-- Seed deeper S.O.D.A ideas and app-builder Academy courses.
-- Data-only migration: no schema or policy changes.

WITH seed_author AS (
  SELECT COALESCE(
    (SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1),
    '00000000-0000-0000-0000-000000000000'::uuid
  ) AS author_id
),
ideas AS (
  SELECT *
  FROM (VALUES
    (
      'district-hospital-ai-command-center',
      'AI command center for district hospitals',
      'A lightweight operations layer that predicts bed pressure, lab delays, medicine stockouts and referral bottlenecks before they become patient harm.',
      'health',
      'District hospitals sit between primary care and specialty hospitals, but most still coordinate through phone calls, spreadsheets and fragmented registers. The wedge is a dashboard plus alerting agent that ingests admissions, lab queues, pharmacy stock and ambulance arrivals, then tells administrators where the next failure will happen.',
      'India is expanding public insurance coverage, ABHA health IDs, digital health rails and district-level capacity at the same time. Hospitals now have enough digital exhaust to coordinate better, but not enough operational software that is affordable and rugged.',
      'Hospital ERPs are heavy, procurement-led and slow to deploy. The unsolved gap is day-to-day throughput: which ward is blocked, which medicine will run out, which lab queue will miss turnaround time, and which referral needs escalation.',
      'Start with one district hospital and one use case: bed and lab queue visibility. Integrate through CSV upload and WhatsApp forms first, then add pharmacy and ambulance modules. Sell to state health missions, hospital PPP operators and NGOs running implementation support.',
      '[{"tier":"Pilot","name":"30-day command center","price":"₹1.5L setup","description":"Map bed, lab and pharmacy bottlenecks for one hospital."},{"tier":"State cluster","name":"District network","price":"₹12L/year","description":"Roll up alerts across 10-20 hospitals."}]'::jsonb,
      'hospital operations software India',
      5400,
      48,
      9,
      9,
      7,
      9,
      '{"best_for":"health ops founders, public-health implementers, AI workflow teams","revenue_model":"implementation fee plus annual SaaS","first_customer":"district hospital administrator or state health program partner"}'::jsonb,
      'B2G / HealthOps',
      'Public healthcare',
      'District hospitals, state health missions, PPP hospital operators',
      'Legacy HMIS vendors',
      'The market is moving from digitizing records to improving operational outcomes. AI agents fit well because many bottlenecks are coordination tasks, not clinical diagnosis.',
      '[{"source":"policy","detail":"ABDM and ABHA adoption increases digital health identity and interoperability pressure."},{"source":"operator signal","detail":"Hospital administrators need live queue and stock visibility more than another static report."}]'::jsonb,
      '[{"keyword":"hospital operations software India","volume":5400,"competition":"medium"},{"keyword":"district hospital management system","volume":1900,"competition":"low"},{"keyword":"healthcare command center","volume":2200,"competition":"medium"}]'::jsonb,
      '{"regulation":"avoid clinical advice in v1; focus on operations","distribution":"sell with health implementation partners","moat":"local workflow data and state-by-state integrations"}'::jsonb,
      ARRAY['health','ai','public-health','operations']::text[],
      ARRAY['High pain','Public impact','AI workflow']::text[]
    ),
    (
      'msme-ai-cash-collection-agent',
      'AI cash-collection agent for MSMEs',
      'A WhatsApp-first agent that follows up on invoices, sends payment links, reconciles UPI receipts and escalates overdue accounts without sounding like a bank.',
      'fintech',
      'Small manufacturers, distributors and service businesses lose working capital because collections live in the owner''s head. The product connects invoices, UPI, WhatsApp and basic accounting, then runs polite multilingual follow-ups and reconciliation.',
      'UPI, account aggregator rails, GST e-invoicing habits and WhatsApp Business adoption create enough infrastructure for automated collections. MSMEs are also under cash-flow pressure, making the ROI easy to explain.',
      'Accounting tools record receivables, but they rarely do the uncomfortable human work of chasing payment. Collection agencies are too harsh for relationship businesses and too expensive for small-ticket invoices.',
      'Launch with Tally/Zoho import and WhatsApp reminders. Add UPI payment links and owner approval for escalations. Expand into credit scoring once repayment behavior is captured.',
      '[{"tier":"Starter","name":"Receivable reminders","price":"₹999/month","description":"WhatsApp follow-ups for up to 100 invoices."},{"tier":"Pro","name":"Collections desk","price":"1% of recovered invoices","description":"Agent workflows, payment links and reconciliation."}]'::jsonb,
      'invoice payment reminder India',
      8100,
      55,
      9,
      8,
      8,
      9,
      '{"best_for":"fintech operators and SMB SaaS founders","revenue_model":"monthly SaaS plus success fee","first_customer":"B2B distributor with 50-500 monthly invoices"}'::jsonb,
      'FinOps SaaS',
      'MSME finance',
      'Manufacturers, distributors, agencies, wholesalers',
      'Accounting software reminder modules',
      'The next wave of MSME software will not just store data; it will perform back-office work through approved agents.',
      '[{"source":"behavior","detail":"Owners already chase payments on WhatsApp, making the product behavior-native."},{"source":"infrastructure","detail":"UPI links and GST invoice data make reconciliation simpler than it was five years ago."}]'::jsonb,
      '[{"keyword":"invoice reminder software","volume":8100,"competition":"medium"},{"keyword":"payment collection software India","volume":3600,"competition":"medium"},{"keyword":"Tally WhatsApp integration","volume":2400,"competition":"low"}]'::jsonb,
      '{"risk":"avoid aggressive recovery language","distribution":"accountants and Tally partners","moat":"payment behavior graph across MSME networks"}'::jsonb,
      ARRAY['fintech','msme','whatsapp','agent']::text[],
      ARRAY['Fast ROI','WhatsApp native','Cash-flow pain']::text[]
    ),
    (
      'export-compliance-copilot',
      'Export compliance copilot for first-time Indian exporters',
      'A guided compliance workspace that helps small exporters classify products, prepare documents, check country rules and avoid shipment holds.',
      'commerce',
      'Thousands of Indian D2C brands and manufacturers want to export, but IEC, HS codes, certificates, labeling, documentation and destination rules are confusing. A copilot can turn fragmented government pages and freight-forwarder advice into a workflow.',
      'Cross-border commerce, ONDC-style digitization, India trade agreements and China+1 sourcing are pushing smaller firms toward export. The constraint is not demand; it is confidence and paperwork.',
      'Freight forwarders solve logistics after the seller is ready. Consultants are expensive and not productized. The gap is pre-shipment readiness for small teams.',
      'Begin with three categories: packaged foods, textiles and cosmetics. Build a document checklist and HS-code assistant, then partner with forwarders for fulfillment handoff.',
      '[{"tier":"Checklist","name":"Export readiness report","price":"₹4,999/report","description":"Category and destination-specific compliance plan."},{"tier":"Workspace","name":"Export desk","price":"₹9,999/month","description":"Document workflows, reminders and forwarder handoff."}]'::jsonb,
      'export documentation India',
      12100,
      42,
      8,
      9,
      7,
      8,
      '{"best_for":"trade-tech founders and compliance operators","revenue_model":"report fees, SaaS, forwarder referral margin","first_customer":"D2C brand exporting to UAE or US"}'::jsonb,
      'TradeTech',
      'Cross-border commerce',
      'D2C brands, manufacturers, export consultants',
      'Freight forwarding portals',
      'AI is strongest here as a checklist and drafting layer, with humans validating edge cases.',
      '[{"source":"trade","detail":"More small Indian brands are testing UAE, US and EU channels."},{"source":"search","detail":"High-intent queries around export documents and HS code classification remain fragmented."}]'::jsonb,
      '[{"keyword":"export documentation India","volume":12100,"competition":"medium"},{"keyword":"HS code finder India","volume":9900,"competition":"high"},{"keyword":"IEC code for export","volume":18100,"competition":"medium"}]'::jsonb,
      '{"risk":"must disclaim legal/tax advice","distribution":"export councils, Shopify agencies, freight partners","moat":"destination-specific compliance knowledge base"}'::jsonb,
      ARRAY['export','compliance','commerce','ai']::text[],
      ARRAY['High intent','China+1','Workflow heavy']::text[]
    ),
    (
      'ev-battery-health-network',
      'Battery health network for electric two-wheelers',
      'A diagnostics and resale trust layer that scores EV two-wheeler batteries for owners, insurers, lenders and used-vehicle buyers.',
      'climate',
      'India''s EV two-wheeler market is growing, but second-hand trust is weak because battery health is opaque. A low-cost diagnostic network can create a standard battery score and unlock resale, insurance and financing.',
      'EV adoption is moving beyond early adopters while battery replacement costs remain a major anxiety. Financing and used sales need a trusted health signal.',
      'OEM apps are siloed, local mechanics lack diagnostic tooling, and resale marketplaces cannot price battery degradation accurately.',
      'Start with portable diagnostic kits for service shops in one city. Issue battery health certificates, then sell APIs to lenders, insurers and used EV marketplaces.',
      '[{"tier":"Certificate","name":"Battery health check","price":"₹399/check","description":"Consumer-facing report for resale or insurance."},{"tier":"Network","name":"Fleet diagnostics","price":"₹99/vehicle/month","description":"Periodic health scoring for fleets and lenders."}]'::jsonb,
      'EV battery health check',
      6600,
      61,
      8,
      8,
      7,
      8,
      '{"best_for":"EV operators, mobility founders, hardware-light diagnostics teams","revenue_model":"per-check fee plus B2B API","first_customer":"used EV dealer or delivery fleet"}'::jsonb,
      'Climate mobility',
      'EV services',
      'EV owners, used dealers, fleets, insurers, lenders',
      'OEM service centers',
      'Trust infrastructure follows adoption. Battery scoring can become the Carfax-style primitive for Indian EV resale.',
      '[{"source":"market","detail":"Two-wheelers dominate Indian EV volume."},{"source":"consumer pain","detail":"Battery replacement cost makes used EV pricing difficult."}]'::jsonb,
      '[{"keyword":"EV battery health check","volume":6600,"competition":"medium"},{"keyword":"used electric scooter battery","volume":1900,"competition":"low"},{"keyword":"EV battery warranty India","volume":4400,"competition":"medium"}]'::jsonb,
      '{"hardware":"partner with diagnostic device vendors first","distribution":"service shops and used dealers","moat":"battery degradation dataset by model and city"}'::jsonb,
      ARRAY['ev','climate','mobility','diagnostics']::text[],
      ARRAY['Trust layer','EV growth','Data moat']::text[]
    ),
    (
      'sme-tender-discovery-agent',
      'Tender discovery agent for SMEs',
      'An agent that finds relevant government and enterprise tenders, summarizes eligibility, drafts checklists and reminds teams before deadlines.',
      'govtech',
      'Indian SMEs often miss tenders because portals are fragmented and documents are dense. A tender agent can monitor opportunities, match them to company capabilities and prepare the first response pack.',
      'Public procurement is digitized but noisy. AI summarization and retrieval make it possible to turn tender discovery from a manual browsing task into a daily workflow.',
      'Existing tender portals sell alerts, not actionable readiness. The gap is eligibility interpretation, document preparation and deadline management.',
      'Begin with one sector such as construction materials or IT services. Build saved capability profiles, eligibility scoring, document extraction and calendar workflows.',
      '[{"tier":"Alerts","name":"Tender watchlist","price":"₹2,999/month","description":"Matched tender alerts and summaries."},{"tier":"Bid desk","name":"Response workspace","price":"₹14,999/month","description":"Eligibility checks, document checklist and draft responses."}]'::jsonb,
      'government tender alerts',
      14800,
      37,
      8,
      8,
      8,
      8,
      '{"best_for":"B2B SaaS and procurement operators","revenue_model":"subscription and bid-prep services","first_customer":"SME selling to government departments"}'::jsonb,
      'Procurement SaaS',
      'Public procurement',
      'SMEs, vendors, bid consultants',
      'Tender alert portals',
      'The value moves from alert volume to confidence: should we bid, what is missing, and what is due today.',
      '[{"source":"workflow","detail":"Tender documents are long and repetitive, ideal for retrieval and summarization."},{"source":"buyer behavior","detail":"SMEs pay when an opportunity is specific and close to revenue."}]'::jsonb,
      '[{"keyword":"government tender alerts","volume":14800,"competition":"medium"},{"keyword":"tender information service","volume":5400,"competition":"medium"},{"keyword":"GeM tender help","volume":3600,"competition":"low"}]'::jsonb,
      '{"risk":"must avoid guaranteeing bid success","distribution":"industry associations and CA networks","moat":"company capability profiles and outcome feedback"}'::jsonb,
      ARRAY['govtech','procurement','sme','ai-agent']::text[],
      ARRAY['Revenue near','Document AI','Daily habit']::text[]
    ),
    (
      'kirana-retail-media-network',
      'Retail media network for kirana stores',
      'A software and ad network that lets kiranas monetize shelf space, WhatsApp catalogs and local purchase signals without becoming modern trade.',
      'commerce',
      'Brands want hyperlocal reach, and kiranas own neighborhood demand signals. The product gives stores simple promotions, digital coupons and WhatsApp campaigns while giving brands measured local activation.',
      'Retail media is growing globally, but India''s offline neighborhood retail remains under-monetized. UPI, WhatsApp catalogs and distributor data make measurement more realistic.',
      'Ad networks do not reach kiranas operationally, and POS vendors focus on billing rather than brand monetization.',
      'Start with FMCG distributors in one city. Offer coupon campaigns and shelf prompts, measure redemptions through UPI/POS uploads, then aggregate store inventory signals.',
      '[{"tier":"Store","name":"Promo kit","price":"Free for stores","description":"Campaign prompts, coupons and WhatsApp catalog boosts."},{"tier":"Brand","name":"Neighborhood campaign","price":"₹50K/campaign","description":"Run local offers across matched kiranas."}]'::jsonb,
      'kirana store marketing',
      4400,
      52,
      8,
      7,
      7,
      8,
      '{"best_for":"commerce operators with distributor access","revenue_model":"brand campaign spend and measurement fees","first_customer":"regional FMCG challenger brand"}'::jsonb,
      'Retail media',
      'Offline commerce',
      'Kirana stores, FMCG brands, distributors',
      'POS and distributor apps',
      'The opportunity is not replacing kiranas; it is adding a lightweight revenue layer on top of existing relationships.',
      '[{"source":"ad market","detail":"Retail media budgets are shifting closer to purchase intent."},{"source":"store behavior","detail":"Kirana owners already run local promotions manually."}]'::jsonb,
      '[{"keyword":"kirana store marketing","volume":4400,"competition":"low"},{"keyword":"retail media network India","volume":1300,"competition":"medium"},{"keyword":"FMCG local promotion","volume":1600,"competition":"low"}]'::jsonb,
      '{"distribution":"distributors first, stores second","moat":"neighborhood transaction and campaign performance data","risk":"attribution quality"}'::jsonb,
      ARRAY['commerce','retail-media','kirana','fmcg']::text[],
      ARRAY['Ad spend','Offline moat','Hyperlocal']::text[]
    ),
    (
      'apartment-water-leak-os',
      'Water leak intelligence for apartments',
      'A sensor-light workflow that helps apartment societies detect leaks, abnormal consumption and tanker fraud before monthly bills explode.',
      'climate',
      'Urban apartment societies are mini-utilities with poor water visibility. The wedge is meter data, anomaly detection and resident workflows for leaks, tankers and borewell usage.',
      'Water stress is becoming a boardroom issue for RWAs as tanker costs rise. Low-cost meters and society management apps have created a path to distribution.',
      'IoT-only solutions are expensive and maintenance-heavy. Society apps track complaints but not water intelligence.',
      'Start with manual meter uploads and tanker logs. Add low-cost mainline meters for high-value societies, then sell monthly water-saving reports and vendor verification.',
      '[{"tier":"Audit","name":"Water loss report","price":"₹25K/society","description":"Baseline consumption and leak estimate."},{"tier":"Monitor","name":"Water intelligence","price":"₹8K/month","description":"Anomaly alerts, tanker logs and resident workflows."}]'::jsonb,
      'apartment water management',
      3600,
      46,
      8,
      8,
      8,
      8,
      '{"best_for":"climate operators and proptech founders","revenue_model":"audit plus monthly monitoring","first_customer":"RWA paying high tanker bills"}'::jsonb,
      'Climate PropTech',
      'Urban water',
      'Apartment societies, facility managers, RWAs',
      'Society management apps',
      'The practical wedge is cost reduction, not climate messaging. Savings can pay for the product in one billing cycle.',
      '[{"source":"urban pain","detail":"Tanker dependence creates measurable recurring costs."},{"source":"workflow","detail":"RWA decisions are committee-led, favoring clear reports and alerts."}]'::jsonb,
      '[{"keyword":"apartment water management","volume":3600,"competition":"low"},{"keyword":"water leak detection India","volume":5400,"competition":"medium"},{"keyword":"RWA water tanker management","volume":900,"competition":"low"}]'::jsonb,
      '{"hardware":"start software-first; add meters later","distribution":"facility managers and RWA networks","moat":"building-level consumption benchmarks"}'::jsonb,
      ARRAY['climate','water','proptech','urban']::text[],
      ARRAY['Cost saving','Climate resilience','Low hardware']::text[]
    ),
    (
      'blue-collar-skill-passport',
      'Skill passport for blue-collar workers',
      'A verified work-history and skill credential wallet for technicians, drivers, caregivers and factory workers moving between employers.',
      'workforce',
      'Blue-collar workers repeatedly prove the same skills to employers with weak documents and informal references. A skill passport combines verified training, job history, assessments and employer feedback.',
      'India needs portable employability signals as manufacturing, logistics, care work and overseas placements grow. Employers want faster screening and workers want better wages.',
      'Job boards optimize applications, not trust. Training institutes issue certificates that employers do not fully believe.',
      'Start with one vertical such as caregivers or EV technicians. Verify training partners, run practical assessments and let employers request authenticated profiles.',
      '[{"tier":"Worker","name":"Skill passport","price":"Free","description":"Verified profile, certificates and work history."},{"tier":"Employer","name":"Verified hiring","price":"₹499/shortlisted worker","description":"Access assessed and reference-backed candidates."}]'::jsonb,
      'blue collar hiring India',
      9900,
      39,
      8,
      8,
      7,
      8,
      '{"best_for":"workforce marketplace founders","revenue_model":"employer access, assessment fees, placement margin","first_customer":"care agency or EV service chain"}'::jsonb,
      'Workforce infrastructure',
      'Skilling and hiring',
      'Workers, training institutes, employers',
      'Job boards and staffing firms',
      'Portable trust is the missing layer between training and employment. The long-term asset is verified work graph data.',
      '[{"source":"labor market","detail":"High churn increases value of portable credentials."},{"source":"policy","detail":"Formal skilling efforts create certificate supply but not always employer trust."}]'::jsonb,
      '[{"keyword":"blue collar hiring India","volume":9900,"competition":"medium"},{"keyword":"skill certificate verification","volume":1900,"competition":"low"},{"keyword":"technician hiring platform","volume":2900,"competition":"medium"}]'::jsonb,
      '{"trust":"requires employer and trainer verification","distribution":"training institutes first","moat":"verified worker graph"}'::jsonb,
      ARRAY['workforce','skills','credentialing','hiring']::text[],
      ARRAY['Trust layer','Large labor market','Portable identity']::text[]
    ),
    (
      'eldercare-family-command-center',
      'Family command center for eldercare',
      'A coordination app for adult children managing parents'' medicines, appointments, helpers, emergencies and local services from another city.',
      'health',
      'Urban migration has separated adult children from aging parents. Families need one trusted layer for reminders, check-ins, medical records, helper coordination and escalation.',
      'India is aging while nuclear families and diaspora households grow. Families already pay informally for helpers and local support; software can organize the chaos.',
      'Eldercare providers are service-heavy and expensive. Pure reminder apps lack trust and local execution.',
      'Start with medicine and appointment coordination plus weekly check-ins. Partner with local diagnostic labs, pharmacies and emergency responders for execution.',
      '[{"tier":"Family","name":"Care command center","price":"₹1,499/month","description":"Reminders, check-ins, records and shared family timeline."},{"tier":"Assisted","name":"Local care desk","price":"₹4,999/month","description":"Adds human coordinator and partner services."}]'::jsonb,
      'elder care services India',
      18100,
      44,
      8,
      9,
      7,
      8,
      '{"best_for":"health service operators and trust-led consumer founders","revenue_model":"subscription plus service marketplace margin","first_customer":"NRI or metro child supporting parents in tier-1/2 city"}'::jsonb,
      'CareTech',
      'Consumer healthcare',
      'Families, eldercare agencies, NRIs',
      'Concierge eldercare providers',
      'The winning product likely combines software trust with human fallback; families pay for reliability, not just reminders.',
      '[{"source":"demographics","detail":"India''s elderly population is growing quickly."},{"source":"behavior","detail":"Family WhatsApp groups already coordinate care informally."}]'::jsonb,
      '[{"keyword":"elder care services India","volume":18100,"competition":"medium"},{"keyword":"medicine reminder for parents","volume":2900,"competition":"low"},{"keyword":"senior care app India","volume":1900,"competition":"low"}]'::jsonb,
      '{"risk":"service quality and liability","distribution":"NRI communities and hospitals","moat":"trusted local care network"}'::jsonb,
      ARRAY['health','eldercare','family','services']::text[],
      ARRAY['Demographic wave','High trust need','Recurring pain']::text[]
    ),
    (
      'factory-quality-vision-ai',
      'AI quality control for small factories',
      'A camera-plus-agent system that spots defects, logs root causes and creates shift-level quality reports for food, textile and component factories.',
      'manufacturing',
      'Small factories often depend on manual inspection and paper logs. Computer vision is now affordable enough for narrow defect detection, while AI agents can turn detections into reports and corrective actions.',
      'PLI, export demand and margin pressure are pushing quality discipline deeper into Indian manufacturing. Cheap cameras and edge models reduce implementation cost.',
      'Enterprise machine-vision vendors are too expensive and too customized for small factories. Manual QC creates inconsistent data.',
      'Start with one visual defect in one category, such as food packaging seal defects or textile stains. Build an install kit, dashboard and weekly quality review workflow.',
      '[{"tier":"Pilot","name":"Defect detection lane","price":"₹75K setup","description":"One camera, one defect class, weekly report."},{"tier":"Factory","name":"Quality agent","price":"₹18K/month","description":"Multi-line monitoring and corrective action logs."}]'::jsonb,
      'manufacturing quality control software',
      5400,
      33,
      8,
      8,
      7,
      8,
      '{"best_for":"industrial AI founders","revenue_model":"hardware setup plus SaaS","first_customer":"export-oriented SME factory"}'::jsonb,
      'Industrial AI',
      'Manufacturing',
      'Food processors, textile units, component factories',
      'Machine vision integrators',
      'The wedge is not generic vision; it is operational reporting that owners can act on each week.',
      '[{"source":"buyer pain","detail":"Rejected batches and rework are direct margin leaks."},{"source":"tech timing","detail":"Edge vision and low-cost cameras make narrow models feasible."}]'::jsonb,
      '[{"keyword":"manufacturing quality control software","volume":5400,"competition":"medium"},{"keyword":"AI defect detection","volume":4400,"competition":"high"},{"keyword":"factory inspection camera","volume":2400,"competition":"medium"}]'::jsonb,
      '{"implementation":"category-specific pilots","distribution":"factory consultants and equipment vendors","moat":"defect datasets by process"}'::jsonb,
      ARRAY['manufacturing','ai','computer-vision','quality']::text[],
      ARRAY['Margin pain','Narrow AI','Export readiness']::text[]
    ),
    (
      'nurse-gulf-placement-copilot',
      'Gulf placement copilot for nurses and caregivers',
      'A training, documentation and interview-prep platform that helps Indian nurses and caregivers qualify for Gulf healthcare jobs faster.',
      'education',
      'Overseas healthcare demand is strong, but candidates struggle with document readiness, English/Arabic workplace language, interview prep and agency opacity. A copilot can create a guided path from eligibility to placement.',
      'Aging Gulf populations, hospital expansion and India''s healthcare workforce supply create a durable corridor. AI tutoring makes personalized prep affordable.',
      'Placement agencies own demand but often underinvest in candidate preparation and transparency. Generic language apps miss healthcare scenarios.',
      'Start with Kerala/Tamil Nadu nursing candidates targeting UAE and Saudi. Build document checklists, role-play interviews, language drills and agency partner dashboards.',
      '[{"tier":"Candidate","name":"Readiness plan","price":"₹999/month","description":"Documents, language drills and interview prep."},{"tier":"Agency","name":"Prepared pipeline","price":"₹2,500/qualified candidate","description":"Candidate readiness score and placement dashboard."}]'::jsonb,
      'nurse jobs in gulf',
      27100,
      35,
      8,
      8,
      8,
      8,
      '{"best_for":"edtech and workforce-placement founders","revenue_model":"candidate subscription plus agency fee","first_customer":"nursing college or placement agency"}'::jsonb,
      'Workforce EdTech',
      'Healthcare migration',
      'Nurses, caregivers, agencies, colleges',
      'Placement agencies',
      'The opportunity is a wedge between training and placement: candidates need a transparent, repeatable path.',
      '[{"source":"search","detail":"High-intent job queries show strong candidate demand."},{"source":"workflow","detail":"Document readiness and interviews are repeatable enough for AI tutoring."}]'::jsonb,
      '[{"keyword":"nurse jobs in gulf","volume":27100,"competition":"medium"},{"keyword":"UAE nursing interview questions","volume":4400,"competition":"low"},{"keyword":"caregiver jobs abroad","volume":9900,"competition":"medium"}]'::jsonb,
      '{"risk":"avoid exploitative placement practices","distribution":"nursing colleges and agencies","moat":"candidate outcome data"}'::jsonb,
      ARRAY['education','workforce','healthcare','migration']::text[],
      ARRAY['High intent','Global demand','AI tutor fit']::text[]
    ),
    (
      'legal-notice-resolution-agent',
      'Legal notice resolution agent for small businesses',
      'An intake and drafting assistant that helps small businesses understand notices, organize evidence and prepare first responses before escalation.',
      'legaltech',
      'Small businesses receive payment disputes, landlord notices, employment claims and customer complaints without knowing what is urgent. The product triages documents and routes serious cases to lawyers.',
      'India''s small businesses transact more digitally, creating more written disputes. LLMs can summarize and structure facts, while lawyers remain needed for final advice.',
      'Legal marketplaces connect to lawyers but do not productize the first 48 hours of a dispute. Owners need clarity before they shop for counsel.',
      'Start with payment disputes and vendor notices. Build upload, summary, deadline extraction, evidence checklist and lawyer handoff.',
      '[{"tier":"Triage","name":"Notice summary","price":"₹499/document","description":"Plain-language summary and urgency checklist."},{"tier":"Resolution","name":"Response pack","price":"₹3,999/case","description":"Evidence bundle and lawyer-reviewed response draft."}]'::jsonb,
      'legal notice reply',
      22200,
      31,
      8,
      8,
      7,
      8,
      '{"best_for":"legaltech founders and lawyer-operators","revenue_model":"document fee plus lawyer marketplace fee","first_customer":"SMB owner with receivable or vendor dispute"}'::jsonb,
      'LegalTech',
      'SMB services',
      'MSMEs, freelancers, agencies, lawyers',
      'Legal marketplaces',
      'The key is not replacing lawyers; it is making the first mile structured, less scary and more affordable.',
      '[{"source":"search","detail":"Legal notice reply queries are high intent and urgent."},{"source":"workflow","detail":"Fact gathering and deadline extraction are repeatable."}]'::jsonb,
      '[{"keyword":"legal notice reply","volume":22200,"competition":"medium"},{"keyword":"payment dispute legal notice","volume":1600,"competition":"low"},{"keyword":"lawyer for small business India","volume":2900,"competition":"medium"}]'::jsonb,
      '{"risk":"must avoid unauthorized legal advice","distribution":"CA and lawyer networks","moat":"case-type templates and lawyer QA loop"}'::jsonb,
      ARRAY['legaltech','smb','ai','disputes']::text[],
      ARRAY['Urgent pain','Human-in-loop','Document AI']::text[]
    ),
    (
      'solar-om-marketplace',
      'Solar O&M marketplace for rooftop owners',
      'A managed marketplace for rooftop solar maintenance: cleaning, inverter checks, generation audits, warranty reminders and technician dispatch.',
      'climate',
      'India is pushing rooftop solar adoption, but post-installation maintenance is fragmented. Owners often discover underperformance months later. A marketplace can protect generation yield.',
      'Government incentives are driving installs, and each install creates a multi-year maintenance need. O&M is recurring and local.',
      'Installers focus on acquisition and installation; after-sales service is inconsistent. Owners lack generation benchmarks and trusted technicians.',
      'Start with residential societies and SME rooftops. Offer quarterly audits, cleaning subscriptions and generation anomaly reports using inverter data or bill uploads.',
      '[{"tier":"Audit","name":"Solar health check","price":"₹1,999/site","description":"Generation and equipment review."},{"tier":"Care plan","name":"O&M subscription","price":"₹699/kW/year","description":"Cleaning, reminders and technician dispatch."}]'::jsonb,
      'solar maintenance India',
      6600,
      58,
      8,
      7,
      8,
      8,
      '{"best_for":"climate operators and service marketplaces","revenue_model":"subscription and technician take-rate","first_customer":"RWA or SME rooftop owner"}'::jsonb,
      'Climate services',
      'Rooftop solar',
      'Homeowners, RWAs, SMEs, installers',
      'Local solar installers',
      'As rooftop solar scales, the market shifts from install growth to yield protection and service quality.',
      '[{"source":"policy","detail":"Rooftop solar incentives increase installed base."},{"source":"customer pain","detail":"Underperformance is hard for owners to diagnose."}]'::jsonb,
      '[{"keyword":"solar maintenance India","volume":6600,"competition":"medium"},{"keyword":"rooftop solar cleaning","volume":1900,"competition":"low"},{"keyword":"solar inverter service","volume":8100,"competition":"medium"}]'::jsonb,
      '{"distribution":"installers and RWAs","moat":"generation benchmarks by city and system type","risk":"service quality consistency"}'::jsonb,
      ARRAY['climate','solar','marketplace','services']::text[],
      ARRAY['Recurring revenue','Policy tailwind','Local services']::text[]
    ),
    (
      'cold-chain-microhub-d2c-foods',
      'Cold-chain microhubs for D2C food brands',
      'Neighborhood cold-chain storage and routing software for small food brands selling dairy, meat, desserts and ready-to-cook products.',
      'logistics',
      'D2C food brands can acquire customers online but struggle with reliable chilled delivery beyond dense metro pockets. Microhubs let multiple brands share cold storage and route density.',
      'Quick commerce has educated customers on freshness, but smaller brands cannot build their own cold chain. Demand is rising for premium regional foods.',
      'Large cold-chain providers are B2B and bulk. Hyperlocal delivery apps are not optimized for shared chilled inventory.',
      'Start with one city and one category such as desserts or meat. Offer shared microhub storage, inventory visibility and scheduled cold routing.',
      '[{"tier":"Brand","name":"Cold shelf","price":"₹4,999/month + delivery","description":"Shared chilled storage and dispatch."},{"tier":"Network","name":"City cold mesh","price":"Custom","description":"Multiple microhubs with routing dashboard."}]'::jsonb,
      'cold chain logistics India',
      12100,
      41,
      8,
      7,
      6,
      8,
      '{"best_for":"logistics operators and D2C commerce founders","revenue_model":"storage fee plus delivery margin","first_customer":"regional premium food brand"}'::jsonb,
      'Food logistics',
      'D2C food',
      'D2C food brands, cloud kitchens, regional producers',
      'Cold-chain logistics providers',
      'The opportunity is operationally hard but defensible; shared demand density creates a local moat.',
      '[{"source":"consumer","detail":"Premium food and fresh categories are expanding online."},{"source":"operations","detail":"Small brands need shared infrastructure, not just software."}]'::jsonb,
      '[{"keyword":"cold chain logistics India","volume":12100,"competition":"medium"},{"keyword":"frozen food delivery India","volume":5400,"competition":"medium"},{"keyword":"D2C food brand logistics","volume":900,"competition":"low"}]'::jsonb,
      '{"risk":"operations complexity","distribution":"brand aggregators and cloud kitchen networks","moat":"microhub density and route data"}'::jsonb,
      ARRAY['logistics','food','d2c','cold-chain']::text[],
      ARRAY['Operational moat','D2C growth','Shared infra']::text[]
    ),
    (
      'school-admin-ai-copilot',
      'AI admin copilot for affordable private schools',
      'A low-cost assistant for school owners that drafts notices, tracks fees, follows up with parents and prepares compliance documents.',
      'education',
      'Affordable private schools run on thin admin teams. Owners juggle admissions, fee reminders, parent messages, timetables and compliance paperwork with little software leverage.',
      'Parents expect digital communication, teachers are overburdened and AI can automate repetitive admin text in Indian languages.',
      'School ERPs are often too complex or poorly adopted. The gap is a simple admin copilot that works through WhatsApp and templates.',
      'Start with parent communication and fee reminders. Add admissions follow-up, compliance document templates and teacher task support.',
      '[{"tier":"Starter","name":"School desk","price":"₹1,999/month","description":"Notices, parent messages and fee reminders."},{"tier":"Plus","name":"Compliance copilot","price":"₹5,999/month","description":"Adds document templates and admissions workflows."}]'::jsonb,
      'school management software India',
      33100,
      29,
      8,
      7,
      8,
      8,
      '{"best_for":"edtech SaaS founders","revenue_model":"school subscription","first_customer":"affordable private school with 300-1500 students"}'::jsonb,
      'EdTech SaaS',
      'K-12 operations',
      'Affordable private schools, school owners, administrators',
      'School ERP vendors',
      'A small focused copilot can beat broad ERPs if it solves daily communication and cash collection.',
      '[{"source":"workflow","detail":"Notices and fee reminders are frequent and language-heavy."},{"source":"buyer","detail":"School owners value anything that protects fee collection and parent trust."}]'::jsonb,
      '[{"keyword":"school management software India","volume":33100,"competition":"high"},{"keyword":"school fee reminder app","volume":1900,"competition":"low"},{"keyword":"WhatsApp for schools","volume":2900,"competition":"medium"}]'::jsonb,
      '{"distribution":"school consultants and local education groups","moat":"localized templates and parent communication data","risk":"price sensitivity"}'::jsonb,
      ARRAY['education','school','ai','whatsapp']::text[],
      ARRAY['Daily use','Fee collection','Language fit']::text[]
    ),
    (
      'construction-material-reuse-exchange',
      'Construction material reuse exchange',
      'A marketplace for surplus tiles, steel, fixtures and demolition materials with verification, logistics and contractor demand matching.',
      'climate',
      'Construction sites waste valuable material because surplus inventory is fragmented and time-sensitive. A reuse exchange can turn leftovers into discounted supply for smaller contractors.',
      'Urban construction, sustainability mandates and material inflation make reuse more attractive. WhatsApp already handles informal resale; software can add trust and logistics.',
      'Scrap dealers capture low-value disposal, not high-value reuse. Marketplaces do not verify quantity, grade or pickup timing.',
      'Start with tiles, sanitaryware and fixtures in one metro. Use site verification, fixed pickup windows and contractor buyer groups.',
      '[{"tier":"Seller","name":"Verified listing","price":"5% success fee","description":"Inspection, listing and buyer matching."},{"tier":"Buyer","name":"Material deal flow","price":"₹999/month","description":"Early access to verified surplus lots."}]'::jsonb,
      'surplus building materials',
      4400,
      36,
      7,
      7,
      7,
      8,
      '{"best_for":"construction-tech and marketplace operators","revenue_model":"take-rate and buyer subscription","first_customer":"mid-size contractor with surplus materials"}'::jsonb,
      'Circular construction',
      'Construction supply',
      'Contractors, developers, architects, reuse buyers',
      'Scrap dealers and classifieds',
      'The market needs trust, speed and logistics more than another listing board.',
      '[{"source":"cost","detail":"Material inflation increases buyer appetite for discounted surplus."},{"source":"behavior","detail":"Informal WhatsApp groups prove demand exists but lacks trust."}]'::jsonb,
      '[{"keyword":"surplus building materials","volume":4400,"competition":"low"},{"keyword":"used construction materials","volume":6600,"competition":"medium"},{"keyword":"demolition material sale","volume":1900,"competition":"low"}]'::jsonb,
      '{"operations":"verification and pickup timing are critical","distribution":"contractor associations","moat":"verified supply network"}'::jsonb,
      ARRAY['construction','climate','marketplace','circular']::text[],
      ARRAY['Waste to value','Inflation hedge','Marketplace']::text[]
    ),
    (
      'clinic-voice-front-desk',
      'Voice front desk for clinics',
      'A multilingual phone and WhatsApp agent that handles appointment booking, follow-ups, directions and basic pre-visit intake for small clinics.',
      'health',
      'Small clinics lose revenue and patient trust when calls go unanswered. A voice agent can act as front desk after hours and during busy OPD periods.',
      'Voice AI quality has improved, patients are comfortable with phone workflows, and clinics need revenue-positive automation rather than full hospital systems.',
      'Practice management tools help after a patient is booked. The missing layer is always-on intake and follow-up in local languages.',
      'Start with appointment booking and reminder calls for dentists, dermatologists and diagnostics centers. Add pre-visit intake and missed-call recovery.',
      '[{"tier":"Clinic","name":"AI receptionist","price":"₹2,999/month","description":"Appointment calls, WhatsApp reminders and missed-call recovery."},{"tier":"Growth","name":"Patient follow-up desk","price":"₹6,999/month","description":"Adds campaigns, reviews and care reminders."}]'::jsonb,
      'clinic appointment booking software',
      9900,
      43,
      8,
      8,
      8,
      8,
      '{"best_for":"voice AI and health SaaS founders","revenue_model":"clinic subscription","first_customer":"single-specialty clinic with high call volume"}'::jsonb,
      'Health SaaS',
      'Clinic operations',
      'Clinics, diagnostics centers, dentists, dermatologists',
      'Practice management systems',
      'Voice agents work when the task is narrow, repetitive and revenue-linked. Clinic booking is exactly that.',
      '[{"source":"workflow","detail":"Missed calls translate directly into lost appointments."},{"source":"tech","detail":"Multilingual speech models are now good enough for constrained booking flows."}]'::jsonb,
      '[{"keyword":"clinic appointment booking software","volume":9900,"competition":"medium"},{"keyword":"AI receptionist for clinic","volume":1300,"competition":"low"},{"keyword":"missed call appointment booking","volume":900,"competition":"low"}]'::jsonb,
      '{"risk":"clinical advice boundaries","distribution":"local clinic marketing agencies","moat":"specialty-specific call scripts and outcomes"}'::jsonb,
      ARRAY['health','voice-ai','clinic','smb']::text[],
      ARRAY['Revenue direct','Voice AI','Local language']::text[]
    ),
    (
      'textile-deadstock-marketplace',
      'Deadstock fabric marketplace for Indian fashion',
      'A verified marketplace for surplus fabric, trims and small-batch textile lots from mills and exporters to designers and D2C brands.',
      'commerce',
      'India has deep textile supply but small designers struggle to find reliable small-batch materials. Mills and exporters sit on deadstock that is hard to liquidate at value.',
      'D2C fashion, sustainability storytelling and small-batch production are rising together. Deadstock supply exists but discovery is messy.',
      'B2B textile portals optimize bulk orders, while Instagram/WhatsApp sourcing lacks verification and repeatability.',
      'Start with two clusters such as Surat and Tiruppur. Verify lots with photos, GSM, composition and minimum order, then offer sample dispatch and logistics.',
      '[{"tier":"Buyer","name":"Verified fabric access","price":"₹999/month","description":"Browse verified deadstock lots and request samples."},{"tier":"Seller","name":"Liquidation service","price":"8% take-rate","description":"Cataloging, buyer matching and logistics support."}]'::jsonb,
      'deadstock fabric India',
      1900,
      51,
      8,
      7,
      7,
      8,
      '{"best_for":"fashion-commerce and textile operators","revenue_model":"take-rate, buyer subscription, logistics margin","first_customer":"small fashion brand sourcing 50-500 meters"}'::jsonb,
      'B2B commerce',
      'Textiles',
      'Fashion brands, designers, mills, exporters',
      'Textile portals and sourcing agents',
      'Trust and detail quality matter more than SKU count; fabric buyers need confidence before ordering.',
      '[{"source":"supply","detail":"Mills and exporters generate surplus lots regularly."},{"source":"demand","detail":"Small fashion brands need lower MOQs and sustainable stories."}]'::jsonb,
      '[{"keyword":"deadstock fabric India","volume":1900,"competition":"low"},{"keyword":"surplus fabric wholesale","volume":4400,"competition":"medium"},{"keyword":"small batch fabric sourcing","volume":900,"competition":"low"}]'::jsonb,
      '{"operations":"catalog accuracy and sample logistics","distribution":"designer communities","moat":"verified seller and fabric metadata"}'::jsonb,
      ARRAY['commerce','textiles','marketplace','sustainability']::text[],
      ARRAY['Surplus supply','D2C fashion','Sustainability']::text[]
    ),
    (
      'medical-tourism-care-concierge',
      'Medical tourism care concierge for India',
      'A trusted planning layer for international patients: hospital matching, treatment estimates, documents, travel, translators and post-care follow-up.',
      'health',
      'India is a major medical tourism destination, but the patient journey is fragmented and anxiety-heavy. A concierge platform can standardize discovery, documentation and care coordination.',
      'Healthcare cost pressure globally and India''s hospital capacity create demand. AI can organize choices, translate records and coordinate tasks before human care managers step in.',
      'Hospitals market independently, agents vary in quality, and patients struggle to compare total cost and trust.',
      'Start with two specialties: dental implants and orthopedics. Build record intake, estimate comparison, visa/travel checklist and partner hospital workflows.',
      '[{"tier":"Plan","name":"Treatment trip plan","price":"$99/report","description":"Hospital shortlist, estimate and travel checklist."},{"tier":"Concierge","name":"Care coordination","price":"8% service fee","description":"End-to-end coordination with hospital and travel partners."}]'::jsonb,
      'medical tourism India',
      18100,
      28,
      8,
      8,
      6,
      7,
      '{"best_for":"health marketplace and concierge operators","revenue_model":"planning fee plus referral/service fee","first_customer":"international patient comparing Indian hospitals"}'::jsonb,
      'Health marketplace',
      'Medical tourism',
      'International patients, hospitals, facilitators',
      'Medical tourism agencies',
      'Trust, transparency and post-care follow-up are the gaps. AI improves intake, but human assurance remains core.',
      '[{"source":"global cost","detail":"Patients seek affordable procedures abroad."},{"source":"workflow","detail":"Medical records, estimates and travel documents are structured enough for a guided workflow."}]'::jsonb,
      '[{"keyword":"medical tourism India","volume":18100,"competition":"medium"},{"keyword":"treatment in India for foreigners","volume":2400,"competition":"low"},{"keyword":"India hospital cost comparison","volume":1600,"competition":"low"}]'::jsonb,
      '{"risk":"medical liability and trust","distribution":"diaspora communities and hospital partners","moat":"patient journey data and verified provider network"}'::jsonb,
      ARRAY['health','marketplace','tourism','concierge']::text[],
      ARRAY['Global demand','Trust heavy','Human-in-loop']::text[]
    ),
    (
      'rural-pharmacy-stock-agent',
      'Stockout agent for rural pharmacies',
      'A purchasing assistant that predicts stockouts, suggests reorder baskets and pools procurement for rural and semi-urban pharmacies.',
      'health',
      'Small pharmacies lose sales and patient trust because inventory decisions are manual and distributor-driven. An agent can forecast demand and recommend reorder baskets from multiple suppliers.',
      'Digital billing, UPI records and distributor APIs create better signals. Medicine availability remains a daily pain outside dense urban pharmacy chains.',
      'Pharmacy software records sales but rarely optimizes purchasing. E-pharmacies focus on consumers, not independent pharmacy operations.',
      'Start with 50 pharmacies in one district. Import sales data, flag stockout risk for chronic medicines and negotiate distributor replenishment bundles.',
      '[{"tier":"Pharmacy","name":"Reorder assistant","price":"₹1,499/month","description":"Stockout forecast and suggested purchase baskets."},{"tier":"Network","name":"Pooled procurement","price":"1.5% of order value","description":"Group buying and supplier routing."}]'::jsonb,
      'pharmacy inventory management India',
      12100,
      34,
      8,
      8,
      7,
      8,
      '{"best_for":"health supply-chain founders","revenue_model":"SaaS plus procurement margin","first_customer":"semi-urban pharmacy with chronic medicine demand"}'::jsonb,
      'Health supply chain',
      'Pharmacy operations',
      'Independent pharmacies, distributors, clinics',
      'Pharmacy billing software',
      'Inventory intelligence is a bridge to procurement power; the long-term upside is pooled buying.',
      '[{"source":"operator pain","detail":"Chronic medicine stockouts directly lose repeat customers."},{"source":"data","detail":"Billing records create reorder signals without heavy integrations."}]'::jsonb,
      '[{"keyword":"pharmacy inventory management India","volume":12100,"competition":"medium"},{"keyword":"medicine stock management","volume":5400,"competition":"medium"},{"keyword":"pharmacy distributor software","volume":1900,"competition":"low"}]'::jsonb,
      '{"distribution":"pharmacy associations and distributors","moat":"district-level demand forecasts","risk":"supplier integration complexity"}'::jsonb,
      ARRAY['health','pharmacy','supply-chain','ai-agent']::text[],
      ARRAY['Daily pain','Procurement moat','Rural health']::text[]
    ),
    (
      'creator-tax-finance-os',
      'Finance OS for Indian creators',
      'A tax, invoicing and income-planning workspace for creators earning from brand deals, platforms, affiliates and international payments.',
      'fintech',
      'Creators operate like small businesses but manage money through screenshots, DMs and messy bank statements. The product organizes income streams, invoices, GST/TDS, taxes and cash planning.',
      'Creator monetization is diversifying while compliance is becoming harder. AI can categorize income, draft invoices and explain tax actions in plain language.',
      'CA services are periodic and manual. Creator tools focus on content, not finance operations.',
      'Start with invoice generation and TDS/GST tracking for Instagram and YouTube creators. Add quarterly tax planning and brand deal profitability dashboards.',
      '[{"tier":"Creator","name":"Finance desk","price":"₹799/month","description":"Invoices, income tracking and tax reminders."},{"tier":"Pro","name":"CA-ready books","price":"₹2,999/month","description":"Reconciliation, GST/TDS support and quarterly reports."}]'::jsonb,
      'creator tax India',
      4400,
      63,
      8,
      7,
      8,
      8,
      '{"best_for":"creator economy and fintech founders","revenue_model":"subscription plus CA partner fee","first_customer":"creator earning ₹50K+/month from brand deals"}'::jsonb,
      'Creator FinTech',
      'Creator economy',
      'Creators, managers, boutique agencies, CAs',
      'CA tools and invoicing apps',
      'Creators need a finance product that matches their income vocabulary: deals, affiliates, payouts and retainers.',
      '[{"source":"behavior","detail":"Creator income is fragmented across platforms and brands."},{"source":"compliance","detail":"GST, TDS and foreign payments create recurring confusion."}]'::jsonb,
      '[{"keyword":"creator tax India","volume":4400,"competition":"low"},{"keyword":"invoicing for creators","volume":1900,"competition":"medium"},{"keyword":"GST for influencers","volume":3600,"competition":"low"}]'::jsonb,
      '{"distribution":"creator managers and agencies","moat":"creator-specific transaction categorization","risk":"tax advice boundaries"}'::jsonb,
      ARRAY['fintech','creator','tax','smb']::text[],
      ARRAY['Creator economy','Compliance pain','Recurring workflow']::text[]
    ),
    (
      'micro-franchise-ops-platform',
      'Micro-franchise ops platform for rural entrepreneurs',
      'An operations layer for brands running village-level micro-franchises: onboarding, stock, tasks, training, incentives and local reporting.',
      'rural-commerce',
      'Rural distribution often depends on micro-entrepreneurs, but brands struggle to manage training, inventory, commissions and proof of activity. A simple app can professionalize the network.',
      'D2C, agri-input, health, finance and energy brands all want rural reach without building full branches. Smartphone penetration makes field ops software possible.',
      'Field sales CRMs are built for employees, not semi-independent franchisees with mixed incentives and local trust roles.',
      'Start with one category such as solar products or agri-inputs. Build onboarding, stock ledger, daily tasks, commission wallet and photo proof.',
      '[{"tier":"Brand","name":"Franchise network OS","price":"₹99/active agent/month","description":"Tasks, training, inventory and incentives."},{"tier":"Launch","name":"Rural activation kit","price":"₹2L setup","description":"Network setup and first 100 entrepreneurs onboarded."}]'::jsonb,
      'rural distribution network',
      2900,
      45,
      8,
      7,
      7,
      8,
      '{"best_for":"rural commerce and field-ops founders","revenue_model":"per-agent SaaS plus setup services","first_customer":"brand managing village entrepreneurs"}'::jsonb,
      'Rural Ops SaaS',
      'Rural distribution',
      'Brands, NGOs, rural entrepreneurs, field teams',
      'Field sales CRM',
      'The wedge is not CRM features; it is incentive design and low-friction execution for semi-formal networks.',
      '[{"source":"distribution","detail":"Rural reach is expensive without trusted local operators."},{"source":"workflow","detail":"Training and proof-of-work can be digitized simply."}]'::jsonb,
      '[{"keyword":"rural distribution network","volume":2900,"competition":"low"},{"keyword":"micro franchise business India","volume":6600,"competition":"medium"},{"keyword":"field sales app India","volume":5400,"competition":"medium"}]'::jsonb,
      '{"distribution":"brands with existing rural pilots","moat":"agent performance and local market data","risk":"training and support load"}'::jsonb,
      ARRAY['rural-commerce','field-ops','franchise','saas']::text[],
      ARRAY['Distribution wedge','Rural growth','Ops layer']::text[]
    ),
    (
      'college-placement-agent',
      'Placement agent for tier-2 colleges',
      'A campus placement copilot that builds student profiles, maps companies, drafts outreach and runs interview-prep loops for placement cells.',
      'education',
      'Tier-2 and tier-3 colleges have placement officers with limited company networks and too much manual coordination. An agent can automate employer outreach and student readiness tracking.',
      'AI hiring tools are spreading, but colleges need the opposite side: student packaging, employer pipeline and interview readiness.',
      'LMS and job boards do not solve placement-cell operations. Resume tools do not create employer demand.',
      'Start with engineering and management colleges. Build student profile scoring, company target lists, outreach sequences and mock interview schedules.',
      '[{"tier":"College","name":"Placement copilot","price":"₹40K/semester","description":"Student readiness, employer outreach and drive tracker."},{"tier":"Outcome","name":"Placement sprint","price":"₹1,500/shortlisted student","description":"Interview prep and employer matching."}]'::jsonb,
      'college placement software',
      6600,
      32,
      8,
      8,
      8,
      8,
      '{"best_for":"edtech and HR-tech founders","revenue_model":"college subscription plus outcome fee","first_customer":"private engineering college placement cell"}'::jsonb,
      'EdTech / HRTech',
      'Campus placements',
      'Colleges, students, employers',
      'Job boards and resume tools',
      'The opportunity is operational: make placement cells more like sales teams with AI-assisted pipelines.',
      '[{"source":"buyer pain","detail":"Placement outcomes are a key college marketing metric."},{"source":"workflow","detail":"Employer outreach and student prep are repeatable sequences."}]'::jsonb,
      '[{"keyword":"college placement software","volume":6600,"competition":"medium"},{"keyword":"campus placement preparation","volume":9900,"competition":"medium"},{"keyword":"placement cell management system","volume":2400,"competition":"low"}]'::jsonb,
      '{"distribution":"college groups and training partners","moat":"student readiness and employer response data","risk":"outcome expectations"}'::jsonb,
      ARRAY['education','hrtech','campus','ai-agent']::text[],
      ARRAY['Outcome pressure','AI workflow','Large supply']::text[]
    ),
    (
      'agri-input-advisory-agent',
      'Agri-input advisory agent for retailers',
      'A decision-support agent for agri-input shops that recommends products, explains usage and records farmer issues in local languages.',
      'agri',
      'Farmers often rely on local retailers for advice on seeds, fertilizers and crop protection. Retailers need better guidance, but brands cannot train every counterperson deeply.',
      'Agri-input complexity is rising while local language AI can deliver practical explanations. Retailers are trusted distribution nodes.',
      'Farmer apps struggle with adoption; retailer workflows already exist. Brand helplines are not embedded at point of sale.',
      'Start with cotton, paddy or vegetable clusters. Build crop-stage recommendations, label explanations and issue logging for retailer counters.',
      '[{"tier":"Retailer","name":"Counter advisor","price":"₹999/month","description":"Local-language product guidance and farmer issue notes."},{"tier":"Brand","name":"Retail intelligence","price":"₹2L/cluster/month","description":"Aggregated demand and issue signals from shops."}]'::jsonb,
      'agri input retailer software',
      1900,
      38,
      8,
      8,
      7,
      8,
      '{"best_for":"agritech and distribution founders","revenue_model":"retailer SaaS plus brand intelligence","first_customer":"regional agri-input distributor"}'::jsonb,
      'Agri SaaS',
      'Agri-input distribution',
      'Retailers, farmers, input brands, distributors',
      'Agri advisory apps',
      'The retailer is the trust point. Software that strengthens the retailer may distribute faster than farmer-only apps.',
      '[{"source":"behavior","detail":"Farmers already ask input shops for advice."},{"source":"brand pain","detail":"Brands need better field issue visibility."}]'::jsonb,
      '[{"keyword":"agri input retailer software","volume":1900,"competition":"low"},{"keyword":"crop advisory app India","volume":9900,"competition":"medium"},{"keyword":"fertilizer recommendation app","volume":2900,"competition":"low"}]'::jsonb,
      '{"risk":"advice liability and regional agronomy","distribution":"distributors first","moat":"localized crop issue dataset"}'::jsonb,
      ARRAY['agri','retail','ai','rural']::text[],
      ARRAY['Trusted channel','Local language','Brand data']::text[]
    ),
    (
      'apprenticeship-matching-os',
      'Apprenticeship matching OS for MSMEs',
      'A marketplace and workflow tool that matches trainees to MSME apprenticeships, tracks attendance, tasks and government paperwork.',
      'workforce',
      'India needs more workplace learning, but MSMEs do not have HR capacity to manage apprenticeships. A platform can reduce paperwork and make trainees productive faster.',
      'Skill development policy and employer demand both favor apprenticeship, while small firms need simple tools and reliable candidates.',
      'Job portals focus on full-time roles. Training providers place candidates but do not manage the apprenticeship workflow.',
      'Start with manufacturing clusters. Build candidate matching, attendance, task logs, stipend reminders and compliance document packs.',
      '[{"tier":"Employer","name":"Apprentice desk","price":"₹999/apprentice/month","description":"Matching, attendance and paperwork."},{"tier":"Provider","name":"Training partner dashboard","price":"₹20K/month","description":"Track placements and outcomes across employers."}]'::jsonb,
      'apprenticeship India',
      22200,
      27,
      8,
      8,
      7,
      7,
      '{"best_for":"workforce and skilling founders","revenue_model":"per-apprentice SaaS plus placement fee","first_customer":"manufacturing MSME cluster association"}'::jsonb,
      'Workforce SaaS',
      'Apprenticeships',
      'MSMEs, trainees, training providers',
      'Job boards and staffing firms',
      'The opportunity is to make apprenticeship easier for employers, not just easier for candidates to apply.',
      '[{"source":"policy","detail":"Apprenticeship is a policy-backed employment pathway."},{"source":"employer pain","detail":"MSMEs lack HR bandwidth for paperwork and tracking."}]'::jsonb,
      '[{"keyword":"apprenticeship India","volume":22200,"competition":"medium"},{"keyword":"apprenticeship portal India","volume":5400,"competition":"medium"},{"keyword":"MSME apprenticeship","volume":900,"competition":"low"}]'::jsonb,
      '{"distribution":"cluster associations and training providers","moat":"employer-task and outcome data","risk":"placement quality"}'::jsonb,
      ARRAY['workforce','apprenticeship','msme','skilling']::text[],
      ARRAY['Policy tailwind','MSME pain','Outcome data']::text[]
    ),
    (
      'ai-local-tourism-operator',
      'AI operator for local tourism businesses',
      'An itinerary, booking and review-response agent for homestays, guides and local tour operators serving domestic travelers.',
      'travel',
      'Small tourism operators know local experiences but struggle with packaging, WhatsApp inquiries, pricing, reviews and follow-up. An AI operator can convert intent into booked itineraries.',
      'Domestic travel, spiritual tourism, weekend trips and creator-led discovery are growing. Operators need software that fits WhatsApp, not enterprise booking tools.',
      'OTAs own discovery but commoditize local operators. Generic CRMs do not build itineraries or respond in local travel language.',
      'Start with homestays and guides in two destinations. Build inquiry capture, itinerary drafts, payment links, review response and upsell workflows.',
      '[{"tier":"Operator","name":"Travel desk agent","price":"₹1,999/month","description":"Inquiry replies, itinerary drafts and payment links."},{"tier":"Destination","name":"Local experience network","price":"8% take-rate","description":"Bundle operators into bookable itineraries."}]'::jsonb,
      'tour operator software India',
      4400,
      36,
      7,
      7,
      8,
      8,
      '{"best_for":"travel operators and AI automation founders","revenue_model":"subscription plus booking take-rate","first_customer":"homestay or local guide with WhatsApp inquiries"}'::jsonb,
      'Travel SaaS',
      'Domestic tourism',
      'Homestays, guides, local tour operators',
      'OTAs and booking tools',
      'The wedge is conversion support for operators who already receive leads but respond slowly or inconsistently.',
      '[{"source":"behavior","detail":"Travel discovery moves through Instagram and WhatsApp before booking."},{"source":"market","detail":"Domestic and spiritual tourism demand is broadening beyond major OTAs."}]'::jsonb,
      '[{"keyword":"tour operator software India","volume":4400,"competition":"medium"},{"keyword":"homestay booking software","volume":1900,"competition":"low"},{"keyword":"itinerary builder India","volume":3600,"competition":"medium"}]'::jsonb,
      '{"distribution":"destination clusters and creator partners","moat":"local itinerary and conversion data","risk":"seasonality"}'::jsonb,
      ARRAY['travel','ai-agent','whatsapp','local-business']::text[],
      ARRAY['Domestic travel','WhatsApp workflow','Local operators']::text[]
    ),
    (
      'upi-dispute-evidence-vault',
      'UPI dispute evidence vault for merchants',
      'A transaction evidence vault that helps merchants resolve UPI reversals, failed payments, charge disputes and customer support cases faster.',
      'fintech',
      'Small merchants lack organized proof when customers dispute payments or UPI failures create confusion. A vault can store receipts, delivery proof, chat context and bank references by transaction.',
      'UPI volume is massive and digital payments are core to small commerce. As more transactions happen digitally, dispute support becomes a merchant pain.',
      'Payment apps show transactions but do not organize operational evidence or support workflows for merchants.',
      'Start with D2C sellers and local service merchants. Auto-ingest payment confirmations, link WhatsApp chats and generate dispute packets.',
      '[{"tier":"Merchant","name":"Payment evidence vault","price":"₹499/month","description":"Receipts, proof and dispute packet generation."},{"tier":"Support","name":"Resolution desk","price":"₹99/case","description":"Guided evidence pack for bank or customer support."}]'::jsonb,
      'UPI payment dispute',
      18100,
      57,
      8,
      7,
      8,
      8,
      '{"best_for":"fintech and merchant SaaS founders","revenue_model":"subscription plus case fee","first_customer":"online seller handling UPI disputes"}'::jsonb,
      'Merchant FinTech',
      'Digital payments',
      'Merchants, D2C sellers, service businesses',
      'Payment gateway dashboards',
      'As payment volume grows, merchant support workflows become a standalone product surface.',
      '[{"source":"search","detail":"UPI dispute queries show recurring confusion."},{"source":"merchant pain","detail":"Evidence is spread across bank apps, WhatsApp, invoices and delivery tools."}]'::jsonb,
      '[{"keyword":"UPI payment dispute","volume":18100,"competition":"medium"},{"keyword":"UPI transaction failed refund","volume":33100,"competition":"high"},{"keyword":"merchant payment dispute","volume":2400,"competition":"medium"}]'::jsonb,
      '{"risk":"bank integration limits","distribution":"payment gateway and seller communities","moat":"case resolution templates and evidence graph"}'::jsonb,
      ARRAY['fintech','upi','merchant','support']::text[],
      ARRAY['Massive volume','Support pain','Evidence workflow']::text[]
    ),
    (
      'warehouse-labor-scheduling-agent',
      'Labor scheduling agent for small warehouses',
      'A scheduling and productivity assistant for warehouses that forecasts workload, plans shifts and tracks attendance for temporary labor.',
      'logistics',
      'Small warehouses manage fluctuating demand with informal labor pools and manual rosters. A scheduling agent can reduce understaffing, overtime and missed dispatches.',
      'E-commerce, quick commerce and regional distribution are expanding warehouse demand beyond large 3PLs. Labor volatility is a daily constraint.',
      'Enterprise WMS tools do not solve labor planning for smaller operators. Staffing firms do not own productivity data.',
      'Start with dispatch workload forecasts from order CSVs. Add roster planning, WhatsApp shift confirmation and attendance-linked productivity reports.',
      '[{"tier":"Warehouse","name":"Shift planner","price":"₹4,999/month","description":"Forecast workload and confirm rosters."},{"tier":"Network","name":"Labor pool manager","price":"₹99/worker/month","description":"Attendance, reliability score and shift history."}]'::jsonb,
      'warehouse workforce management',
      5400,
      40,
      8,
      7,
      8,
      8,
      '{"best_for":"logistics SaaS and staffing founders","revenue_model":"warehouse subscription and per-worker fee","first_customer":"regional warehouse with daily temp labor"}'::jsonb,
      'Logistics Ops',
      'Warehousing',
      'Warehouses, 3PLs, staffing agencies',
      'WMS and staffing tools',
      'The opportunity sits between WMS and staffing: forecast the work, then confirm the people.',
      '[{"source":"operations","detail":"Dispatch failures often trace back to shift planning."},{"source":"market","detail":"Regional warehousing is growing outside top-tier operators."}]'::jsonb,
      '[{"keyword":"warehouse workforce management","volume":5400,"competition":"medium"},{"keyword":"warehouse shift scheduling","volume":3600,"competition":"medium"},{"keyword":"temporary labour management","volume":1600,"competition":"low"}]'::jsonb,
      '{"distribution":"regional 3PLs and staffing agencies","moat":"worker reliability and workload data","risk":"attendance data quality"}'::jsonb,
      ARRAY['logistics','workforce','warehouse','ai-agent']::text[],
      ARRAY['Ops pain','Labor volatility','Forecasting']::text[]
    ),
    (
      'regional-language-customer-support-qa',
      'Regional-language support QA for Indian contact centers',
      'A QA and coaching layer that audits Hindi, Tamil, Telugu, Bengali and Marathi support calls for compliance, empathy and resolution quality.',
      'ai',
      'Contact centers record thousands of regional-language calls but QA samples are tiny. AI can transcribe, score and coach agents across Indian languages where English-first tools fall short.',
      'Speech models for Indian languages are improving, and companies are pushing support deeper into Bharat. Quality monitoring must catch up.',
      'Existing call-center QA tools are expensive and English-heavy. Manual QA misses most calls.',
      'Start with one language and one vertical such as lending or healthcare. Offer transcription, scorecards, escalation detection and coachable snippets.',
      '[{"tier":"QA","name":"Call audit","price":"₹0.80/minute","description":"Transcription and quality scoring."},{"tier":"Coaching","name":"Agent improvement loop","price":"₹999/agent/month","description":"Weekly coaching cards and compliance alerts."}]'::jsonb,
      'call center quality monitoring software',
      8100,
      34,
      8,
      8,
      7,
      8,
      '{"best_for":"AI speech and BPO SaaS founders","revenue_model":"usage plus per-agent subscription","first_customer":"BPO handling regional-language support"}'::jsonb,
      'AI QA',
      'Customer support',
      'BPOs, fintechs, healthcare support teams',
      'Call center QA suites',
      'Indian-language QA is a wedge where global tools are weaker and local context matters.',
      '[{"source":"tech","detail":"Indic ASR quality is improving quickly."},{"source":"buyer pain","detail":"Manual QA samples too little to manage compliance risk."}]'::jsonb,
      '[{"keyword":"call center quality monitoring software","volume":8100,"competition":"medium"},{"keyword":"Hindi call transcription","volume":1900,"competition":"low"},{"keyword":"customer support QA software","volume":6600,"competition":"medium"}]'::jsonb,
      '{"distribution":"BPOs and regulated support teams","moat":"language-specific QA rubrics and acoustic data","risk":"ASR accuracy by dialect"}'::jsonb,
      ARRAY['ai','support','speech','bpo']::text[],
      ARRAY['Indic AI','Compliance','BPO wedge']::text[]
    ),
    (
      'micro-insurance-claims-copilot',
      'Claims copilot for micro-insurance',
      'A guided claim-filing assistant for low-ticket health, crop, device and accident insurance sold through partners.',
      'fintech',
      'Micro-insurance is only trusted if claims feel simple. Customers often abandon claims because documents, deadlines and status tracking are confusing.',
      'Embedded insurance is spreading through fintech, commerce and agri channels. Claims operations will become the trust bottleneck.',
      'Insurers have claim portals, but partner-led customers need handholding in local languages and through WhatsApp.',
      'Start with device protection or accident policies. Build document checklists, photo capture, deadline reminders and partner dashboards.',
      '[{"tier":"Partner","name":"Claims assistant","price":"₹15/active policy/year","description":"Guided claim filing and status nudges."},{"tier":"Insurer","name":"Claims ops dashboard","price":"Custom","description":"Cleaner intake, fewer incomplete claims and partner analytics."}]'::jsonb,
      'micro insurance claims',
      1900,
      49,
      8,
      8,
      7,
      8,
      '{"best_for":"insurtech and embedded-finance founders","revenue_model":"per-policy SaaS or claim intake fee","first_customer":"embedded insurance distributor"}'::jsonb,
      'InsurTech',
      'Embedded insurance',
      'Insurers, fintech partners, agri platforms, device sellers',
      'Insurer claim portals',
      'The value is trust. A smoother claim experience increases renewal and partner credibility.',
      '[{"source":"market","detail":"Embedded insurance expands distribution to new low-ticket users."},{"source":"workflow","detail":"Incomplete documents are a repeatable claim bottleneck."}]'::jsonb,
      '[{"keyword":"micro insurance claims","volume":1900,"competition":"low"},{"keyword":"insurance claim status app","volume":6600,"competition":"medium"},{"keyword":"embedded insurance India","volume":2400,"competition":"medium"}]'::jsonb,
      '{"distribution":"embedded insurance partners","moat":"claim document and resolution data","risk":"insurer integration cycles"}'::jsonb,
      ARRAY['fintech','insurtech','claims','whatsapp']::text[],
      ARRAY['Trust bottleneck','Embedded growth','Workflow AI']::text[]
    )
  ) AS v(
    slug, title, tagline, sector, summary, why_now, market_gap, execution_plan, offer, keyword,
    volume, growth_pct, score_opportunity, score_problem, score_feasibility, score_why_now,
    business_fit, type_label, market_label, target_label, main_competitor, trend_analysis,
    community_signals, top_keywords, framework_fit, tags, badges
  )
)
INSERT INTO public.soda_ideas (
  slug, title, tagline, sector, summary, why_now, market_gap, execution_plan, offer, keyword,
  volume, growth_pct, score_opportunity, score_problem, score_feasibility, score_why_now,
  business_fit, type_label, market_label, target_label, main_competitor, trend_analysis,
  community_signals, top_keywords, framework_fit, tags, badges, status, published_at, featured_on, created_by
)
SELECT
  i.slug, i.title, i.tagline, i.sector, i.summary, i.why_now, i.market_gap, i.execution_plan,
  i.offer, i.keyword, i.volume, i.growth_pct, i.score_opportunity, i.score_problem,
  i.score_feasibility, i.score_why_now, i.business_fit, i.type_label, i.market_label,
  i.target_label, i.main_competitor, i.trend_analysis, i.community_signals, i.top_keywords,
  i.framework_fit, i.tags, i.badges, 'published', now(), current_date, seed_author.author_id
FROM ideas i
CROSS JOIN seed_author
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  tagline = EXCLUDED.tagline,
  sector = EXCLUDED.sector,
  summary = EXCLUDED.summary,
  why_now = EXCLUDED.why_now,
  market_gap = EXCLUDED.market_gap,
  execution_plan = EXCLUDED.execution_plan,
  offer = EXCLUDED.offer,
  keyword = EXCLUDED.keyword,
  volume = EXCLUDED.volume,
  growth_pct = EXCLUDED.growth_pct,
  score_opportunity = EXCLUDED.score_opportunity,
  score_problem = EXCLUDED.score_problem,
  score_feasibility = EXCLUDED.score_feasibility,
  score_why_now = EXCLUDED.score_why_now,
  business_fit = EXCLUDED.business_fit,
  type_label = EXCLUDED.type_label,
  market_label = EXCLUDED.market_label,
  target_label = EXCLUDED.target_label,
  main_competitor = EXCLUDED.main_competitor,
  trend_analysis = EXCLUDED.trend_analysis,
  community_signals = EXCLUDED.community_signals,
  top_keywords = EXCLUDED.top_keywords,
  framework_fit = EXCLUDED.framework_fit,
  tags = EXCLUDED.tags,
  badges = EXCLUDED.badges,
  status = 'published',
  published_at = COALESCE(public.soda_ideas.published_at, now()),
  featured_on = EXCLUDED.featured_on;

WITH seed_author AS (
  SELECT COALESCE(
    (SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1),
    '00000000-0000-0000-0000-000000000000'::uuid
  ) AS author_id
),
course_seed(slug, title, summary, sort_order) AS (
  VALUES
    ('lovable-from-prompt-to-mvp', 'Lovable: from prompt to MVP', 'A practical path for turning a product idea into a working Lovable app with clean scope, data model, auth, and launch checklist.', 10),
    ('bolt-new-full-stack-builder', 'Bolt.new: full-stack builder workflow', 'Learn how to scope, generate, debug and deploy a full-stack app with Bolt.new while keeping the codebase understandable.', 20),
    ('cursor-agentic-codebase', 'Cursor: agentic coding for real apps', 'Use Cursor as an engineering partner: plan features, edit safely, review diffs, write tests and ship production-quality changes.', 30),
    ('replit-agent-launch-lab', 'Replit Agent: launch lab', 'Build and deploy small apps with Replit Agent, then harden the result with environment variables, database checks and iteration loops.', 40),
    ('v0-interface-to-production', 'v0: interface to production', 'Design high-quality interfaces with v0, then convert them into product-ready flows with data, auth, states and responsive polish.', 50)
),
upserted_courses AS (
  INSERT INTO public.courses (slug, title, summary, cover_url, status, created_by, published_at, sort_order)
  SELECT slug, title, summary, NULL, 'published', seed_author.author_id, now(), sort_order
  FROM course_seed
  CROSS JOIN seed_author
  ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    status = 'published',
    published_at = COALESCE(public.courses.published_at, now()),
    sort_order = EXCLUDED.sort_order
  RETURNING id, slug
),
module_seed(course_slug, module_order, title, summary) AS (
  VALUES
    ('lovable-from-prompt-to-mvp', 0, 'Ship the Lovable MVP', 'Scope tightly, generate carefully, connect the basics and prepare a credible launch.'),
    ('bolt-new-full-stack-builder', 0, 'Build the Bolt app loop', 'Prompt, inspect, fix, persist data and deploy with a repeatable full-stack rhythm.'),
    ('cursor-agentic-codebase', 0, 'Work with Cursor like an engineer', 'Use agentic coding without losing architectural control or review discipline.'),
    ('replit-agent-launch-lab', 0, 'Launch with Replit Agent', 'Move from app idea to deployed prototype with environment, data and QA basics.'),
    ('v0-interface-to-production', 0, 'Take v0 beyond the mockup', 'Turn generated UI into usable product screens with states, data and responsive craft.')
),
inserted_modules AS (
  INSERT INTO public.course_modules (course_id, title, summary, sort_order)
  SELECT c.id, m.title, m.summary, m.module_order
  FROM module_seed m
  JOIN upserted_courses c ON c.slug = m.course_slug
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.course_modules existing
    WHERE existing.course_id = c.id
      AND existing.title = m.title
      AND existing.sort_order = m.module_order
  )
  RETURNING id, course_id, title, sort_order
),
all_modules AS (
  SELECT id, course_id, title, sort_order FROM inserted_modules
  UNION ALL
  SELECT existing.id, existing.course_id, existing.title, existing.sort_order
  FROM public.course_modules existing
  JOIN upserted_courses c ON c.id = existing.course_id
  JOIN module_seed m
    ON m.course_slug = c.slug
   AND m.title = existing.title
   AND m.module_order = existing.sort_order
),
lesson_seed(course_slug, module_order, lesson_slug, title, content, video_url, duration_mins, sort_order) AS (
  VALUES
    ('lovable-from-prompt-to-mvp', 0, 'define-the-mvp-contract', 'Define the MVP contract', 'Outcome: write a one-page product contract before prompting. Steps: name the user, painful job, core workflow, data objects, permissions, and one success metric. Deliverable: a prompt brief that says what the app must do and what it must not do yet.', 'https://www.youtube.com/results?search_query=Lovable+AI+tutorial+build+app+2026+latest', 18, 0),
    ('lovable-from-prompt-to-mvp', 0, 'generate-the-first-app', 'Generate the first app', 'Outcome: create a first Lovable build without overprompting. Steps: paste the MVP contract, ask for one primary user flow, inspect screens, fix navigation, remove decorative bloat and keep the data model simple.', 'https://www.youtube.com/results?search_query=Lovable+AI+app+builder+tutorial+2026+latest', 24, 1),
    ('lovable-from-prompt-to-mvp', 0, 'connect-data-and-auth', 'Connect data and auth', 'Outcome: make the app stateful. Steps: identify tables, decide public versus private data, wire login, add empty states, test signed-out and signed-in flows, and document anything that would need RLS review.', 'https://www.youtube.com/results?search_query=Lovable+Supabase+auth+tutorial+2026+latest', 28, 2),
    ('lovable-from-prompt-to-mvp', 0, 'polish-the-social-flow', 'Polish the social flow', 'Outcome: make the app feel real. Steps: reduce empty space, add feed/profile/detail states, improve mobile spacing, add real labels, and test the core flow with one example user story.', 'https://www.youtube.com/results?search_query=Lovable+responsive+UI+tutorial+2026+latest', 22, 3),
    ('lovable-from-prompt-to-mvp', 0, 'launch-and-iterate', 'Launch and iterate', 'Outcome: ship a small credible MVP. Steps: write QA checklist, test auth, test mobile, publish, collect five user reactions, and turn feedback into the next prompt batch.', 'https://www.youtube.com/results?search_query=Lovable+deploy+app+tutorial+2026+latest', 20, 4),
    ('bolt-new-full-stack-builder', 0, 'scope-for-bolt', 'Scope for Bolt.new', 'Outcome: prepare a prompt that Bolt can turn into a coherent full-stack app. Steps: define pages, components, storage, API calls, edge cases and constraints before generating.', 'https://www.youtube.com/results?search_query=Bolt.new+tutorial+build+full+stack+app+2026+latest', 18, 0),
    ('bolt-new-full-stack-builder', 0, 'inspect-the-generated-code', 'Inspect generated code', 'Outcome: learn what Bolt created before asking for changes. Steps: review routes, state, package choices, data flow and styling; then write a fix list in priority order.', 'https://www.youtube.com/results?search_query=Bolt.new+AI+coding+tutorial+2026+latest', 24, 1),
    ('bolt-new-full-stack-builder', 0, 'add-real-data', 'Add real data safely', 'Outcome: replace mock state with durable storage. Steps: identify entities, add simple CRUD, show loading/error states, avoid hidden failures and keep migrations separate from UI changes.', 'https://www.youtube.com/results?search_query=Bolt.new+Supabase+tutorial+2026+latest', 30, 2),
    ('bolt-new-full-stack-builder', 0, 'debug-with-discipline', 'Debug with discipline', 'Outcome: fix bugs without thrashing the codebase. Steps: reproduce, read the stack trace, isolate files, ask Bolt for narrow patches, run tests and review diffs.', 'https://www.youtube.com/results?search_query=Bolt.new+debugging+tutorial+2026+latest', 20, 3),
    ('bolt-new-full-stack-builder', 0, 'deploy-and-harden', 'Deploy and harden', 'Outcome: prepare the app for testers. Steps: set environment variables, run build, check mobile, handle auth errors, protect secrets and create a short release note.', 'https://www.youtube.com/results?search_query=Bolt.new+deploy+app+tutorial+2026+latest', 22, 4),
    ('cursor-agentic-codebase', 0, 'read-before-editing', 'Read before editing', 'Outcome: use Cursor to understand before changing. Steps: map files, ask for data flow, identify ownership boundaries and write the smallest patch plan.', 'https://www.youtube.com/results?search_query=Cursor+AI+tutorial+codebase+2026+latest', 18, 0),
    ('cursor-agentic-codebase', 0, 'prompt-for-small-diffs', 'Prompt for small diffs', 'Outcome: get useful agent edits. Steps: give context, state constraints, request focused patches, reject broad rewrites and keep unrelated files untouched.', 'https://www.youtube.com/results?search_query=Cursor+AI+agent+tutorial+2026+latest', 22, 1),
    ('cursor-agentic-codebase', 0, 'review-agent-output', 'Review agent output', 'Outcome: catch regressions before they land. Steps: inspect imports, state changes, auth assumptions, accessibility and data error paths; then run type/build checks.', 'https://www.youtube.com/results?search_query=Cursor+AI+code+review+tutorial+2026+latest', 26, 2),
    ('cursor-agentic-codebase', 0, 'write-tests-and-checks', 'Write tests and checks', 'Outcome: add verification where risk is highest. Steps: choose smoke, unit or integration checks, run them locally and document what remains untested.', 'https://www.youtube.com/results?search_query=Cursor+AI+testing+tutorial+2026+latest', 24, 3),
    ('cursor-agentic-codebase', 0, 'ship-a-feature-branch', 'Ship a feature branch', 'Outcome: finish like an engineer. Steps: summarize changes, check git diff, write commit message, push and create a PR with risks and verification.', 'https://www.youtube.com/results?search_query=Cursor+AI+GitHub+workflow+tutorial+2026+latest', 18, 4),
    ('replit-agent-launch-lab', 0, 'start-with-a-runnable-spec', 'Start with a runnable spec', 'Outcome: write a spec Replit Agent can execute. Steps: describe routes, state, data and deployment needs; keep v1 small enough to launch in one session.', 'https://www.youtube.com/results?search_query=Replit+Agent+tutorial+build+app+2026+latest', 18, 0),
    ('replit-agent-launch-lab', 0, 'build-and-run', 'Build and run', 'Outcome: generate the app and keep it running. Steps: inspect files, start the server, test the main route and fix obvious runtime errors before adding features.', 'https://www.youtube.com/results?search_query=Replit+Agent+AI+app+tutorial+2026+latest', 22, 1),
    ('replit-agent-launch-lab', 0, 'add-env-and-storage', 'Add env and storage', 'Outcome: prepare the app for real use. Steps: set secrets, add database/storage choices, avoid hardcoded keys and check failure states.', 'https://www.youtube.com/results?search_query=Replit+Agent+database+tutorial+2026+latest', 26, 2),
    ('replit-agent-launch-lab', 0, 'qa-the-prototype', 'QA the prototype', 'Outcome: move from demo to usable. Steps: test empty states, bad inputs, mobile, auth redirects, slow network assumptions and deployment URLs.', 'https://www.youtube.com/results?search_query=Replit+Agent+deploy+tutorial+2026+latest', 22, 3),
    ('replit-agent-launch-lab', 0, 'publish-and-measure', 'Publish and measure', 'Outcome: launch with a feedback loop. Steps: deploy, invite testers, add a feedback form, track bugs and prioritize the next two improvements.', 'https://www.youtube.com/results?search_query=Replit+Agent+launch+app+2026+latest', 20, 4),
    ('v0-interface-to-production', 0, 'design-the-interface-brief', 'Design the interface brief', 'Outcome: generate better UI by writing a better brief. Steps: define user, density, states, data fields, mobile behavior and design constraints before prompting v0.', 'https://www.youtube.com/results?search_query=Vercel+v0+tutorial+build+app+2026+latest', 16, 0),
    ('v0-interface-to-production', 0, 'generate-and-trim', 'Generate and trim', 'Outcome: get a clean UI without excess. Steps: generate the screen, remove marketing bloat, tighten spacing, check hierarchy and keep only controls users need.', 'https://www.youtube.com/results?search_query=v0+AI+UI+tutorial+2026+latest', 22, 1),
    ('v0-interface-to-production', 0, 'connect-states-and-data', 'Connect states and data', 'Outcome: turn a static component into a product screen. Steps: add loading, empty, error and success states; wire sample data first, then real data.', 'https://www.youtube.com/results?search_query=v0+React+component+tutorial+2026+latest', 28, 2),
    ('v0-interface-to-production', 0, 'make-it-responsive', 'Make it responsive', 'Outcome: make the interface mobile-ready. Steps: test breakpoints, reduce horizontal overflow, size buttons correctly and avoid text overlap.', 'https://www.youtube.com/results?search_query=v0+responsive+UI+tutorial+2026+latest', 20, 3),
    ('v0-interface-to-production', 0, 'handoff-to-codebase', 'Handoff to codebase', 'Outcome: integrate v0 output cleanly. Steps: match design tokens, replace placeholder logic, use existing components and run build before committing.', 'https://www.youtube.com/results?search_query=v0+to+Next.js+production+tutorial+2026+latest', 24, 4)
),
upserted_lessons AS (
  INSERT INTO public.lessons (module_id, slug, title, content, video_url, duration_mins, sort_order, status)
  SELECT am.id, l.lesson_slug, l.title, l.content, l.video_url, l.duration_mins, l.sort_order, 'published'
  FROM lesson_seed l
  JOIN upserted_courses c ON c.slug = l.course_slug
  JOIN all_modules am ON am.course_id = c.id AND am.sort_order = l.module_order
  ON CONFLICT (module_id, slug) DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    video_url = EXCLUDED.video_url,
    duration_mins = EXCLUDED.duration_mins,
    sort_order = EXCLUDED.sort_order,
    status = 'published'
  RETURNING id, slug, title
),
final_lessons AS (
  SELECT il.id
  FROM upserted_lessons il
  WHERE il.slug IN ('launch-and-iterate', 'deploy-and-harden', 'ship-a-feature-branch', 'publish-and-measure', 'handoff-to-codebase')
),
upserted_quizzes AS (
  INSERT INTO public.quizzes (lesson_id, title, passing_score)
  SELECT id, 'Launch readiness check', 70
  FROM final_lessons
  ON CONFLICT (lesson_id) DO UPDATE SET
    title = EXCLUDED.title,
    passing_score = EXCLUDED.passing_score
  RETURNING id, lesson_id
),
inserted_questions AS (
  INSERT INTO public.quiz_questions (quiz_id, prompt, sort_order)
  SELECT id, 'What is the strongest sign that this app-builder project is ready for outside testers?', 0
  FROM upserted_quizzes q
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.quiz_questions existing
    WHERE existing.quiz_id = q.id
      AND existing.prompt = 'What is the strongest sign that this app-builder project is ready for outside testers?'
  )
  RETURNING id, quiz_id
),
target_questions AS (
  SELECT id, quiz_id FROM inserted_questions
  UNION ALL
  SELECT existing.id, existing.quiz_id
  FROM public.quiz_questions existing
  JOIN upserted_quizzes q ON q.id = existing.quiz_id
  WHERE existing.prompt = 'What is the strongest sign that this app-builder project is ready for outside testers?'
),
option_seed(label, is_correct, sort_order) AS (
  VALUES
    ('The main flow has been tested with realistic data, mobile layout, auth/session states and a short feedback loop.', true, 0),
    ('The hero section looks polished, even if the core workflow is not connected yet.', false, 1),
    ('The builder generated many screens, even if no one has tried the product.', false, 2)
)
INSERT INTO public.quiz_options (question_id, label, is_correct, sort_order)
SELECT q.id, o.label, o.is_correct, o.sort_order
FROM target_questions q
CROSS JOIN option_seed o
WHERE NOT EXISTS (
  SELECT 1
  FROM public.quiz_options existing
  WHERE existing.question_id = q.id
    AND existing.label = o.label
);
