// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { resolveBrowserSupabaseConfig } from "./runtime-config";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";
const { url, publishableKey } = resolveBrowserSupabaseConfig(import.meta.env);

export const supabase = createClient<Database>(url, publishableKey, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
    detectSessionInUrl: isBrowser,
    flowType: "pkce",
  },
});
